# Scrape the movie budges

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from sqlalchemy import create_engine

In [2]:
# Define a function to scrape the movies
def scrape_movies(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.text.encode('ascii', 'ignore').decode('ascii'), 'html.parser')
    df = []
    for tr in soup.find_all('tr')[1:]:
        tds = tr.find_all('td')
        data = [td.text for td in tds]
        df.append(data) 
    return df

In [3]:
# Original
# Define a function to scrape the movies
# def scrape_movies(url):
#     response = requests.get(url)
#     soup = BeautifulSoup(response.text, 'html.parser')
#     df = []
#     for tr in soup.find_all('tr')[1:]:
#         tds = tr.find_all('td')
#         data = [td.text.strip() for td in tds]
#         df.append(data) 
#     return df

In [4]:
link = []
for i in range(6):
    for j in range (10):
        if i == 0:
            if j == 0:
                link.append('/all')
            else:
                link.append('/all/'+str(j)+'01')
        else: 
            link.append('/all/'+str(i)+str(j)+'01')

In [5]:
for i in range(len(link)):
    print(str(i)+': '+link[i])

0: /all
1: /all/101
2: /all/201
3: /all/301
4: /all/401
5: /all/501
6: /all/601
7: /all/701
8: /all/801
9: /all/901
10: /all/1001
11: /all/1101
12: /all/1201
13: /all/1301
14: /all/1401
15: /all/1501
16: /all/1601
17: /all/1701
18: /all/1801
19: /all/1901
20: /all/2001
21: /all/2101
22: /all/2201
23: /all/2301
24: /all/2401
25: /all/2501
26: /all/2601
27: /all/2701
28: /all/2801
29: /all/2901
30: /all/3001
31: /all/3101
32: /all/3201
33: /all/3301
34: /all/3401
35: /all/3501
36: /all/3601
37: /all/3701
38: /all/3801
39: /all/3901
40: /all/4001
41: /all/4101
42: /all/4201
43: /all/4301
44: /all/4401
45: /all/4501
46: /all/4601
47: /all/4701
48: /all/4801
49: /all/4901
50: /all/5001
51: /all/5101
52: /all/5201
53: /all/5301
54: /all/5401
55: /all/5501
56: /all/5601
57: /all/5701
58: /all/5801
59: /all/5901

In [6]:
len(link)

60

In [7]:
result = scrape_movies('https://www.the-numbers.com/movie/budgets'+link[0])
for n in range(1, len(link)): 
    df = scrape_movies('https://www.the-numbers.com/movie/budgets'+link[n])
    if len(df) > 0:
        result += df

In [8]:
result

[['1',
  'Dec 18, 2009',
  'Avatar',
  '$425,000,000',
  '$760,507,625',
  '$2,789,705,275'],
 ['2',
  'May 20, 2011',
  'Pirates of the Caribbean: On Stranger Tides',
  '$410,600,000',
  '$241,063,875',
  '$1,045,663,875'],
 ['3',
  'Apr 26, 2019',
  'Avengers: Endgame',
  '$400,000,000',
  '$855,869,749',
  '$2,791,767,021'],
 ['4',
  'Jun 7, 2019',
  'Dark Phoenix',
  '$350,000,000',
  '$65,504,972',
  '$246,209,283'],
 ['5',
  'May 1, 2015',
  'Avengers: Age of Ultron',
  '$330,600,000',
  '$459,005,868',
  '$1,403,013,963'],
 ['6',
  'Dec 15, 2017',
  'Star Wars Ep. VIII: The Last Jedi',
  '$317,000,000',
  '$620,181,382',
  '$1,316,721,747'],
 ['7',
  'Dec 18, 2015',
  'Star Wars Ep. VII: The Force Awakens',
  '$306,000,000',
  '$936,662,225',
  '$2,053,311,220'],
 ['8',
  'Apr 27, 2018',
  'Avengers: Infinity War',
  '$300,000,000',
  '$678,815,482',
  '$2,048,134,200'],
 ['9',
  'May 24, 2007',
  'Pirates of the Caribbean: At Worlds End',
  '$300,000,000',
  '$309,420,425',
  '$963,420,425'],
 ['10',
  'Nov 17, 2017',
  'Justice League',
  '$300,000,000',
  '$229,024,295',
  '$655,945,209'],
 ['11',
  'Nov 6, 2015',
  'Spectre',
  '$300,000,000',
  '$200,074,175',
  '$879,620,923'],
 ['12',
  'Jul 20, 2012',
  'The Dark Knight Rises',
  '$275,000,000',
  '$448,139,099',
  '$1,084,439,099'],
 ['13',
  'May 25, 2018',
  'Solo: A Star Wars Story',
  '$275,000,000',
  '$213,767,512',
  '$393,151,347'],
 ['14',
  'Jul 2, 2013',
  'The Lone Ranger',
  '$275,000,000',
  '$89,302,115',
  '$260,002,115'],
 ['15',
  'Mar 9, 2012',
  'John Carter',
  '$275,000,000',
  '$73,058,679',
  '$282,778,100'],
 ['16',
  'Nov 24, 2010',
  'Tangled',
  '$260,000,000',
  '$200,821,936',
  '$586,477,240'],
 ['17',
  'May 4, 2007',
  'Spider-Man 3',
  '$258,000,000',
  '$336,530,303',
  '$894,860,230'],
 ['18',
  'May 6, 2016',
  'Captain America: Civil War',
  '$250,000,000',
  '$408,084,349',
  '$1,140,069,413'],
 ['19',
  'Mar 25, 2016',
  'Batman v Superman: Dawn of Justice',
  '$250,000,000',
  '$330,360,194',
  '$867,500,281'],
 ['20',
  'Dec 14, 2012',
  'The Hobbit: An Unexpected Journey',
  '$250,000,000',
  '$303,003,568',
  '$1,017,003,568'],
 ['21',
  'Jul 15, 2009',
  'Harry Potter and the Half-Blood Prince',
  '$250,000,000',
  '$302,089,278',
  '$935,213,767'],
 ['22',
  'Dec 13, 2013',
  'The Hobbit: The Desolation of Smaug',
  '$250,000,000',
  '$258,366,855',
  '$960,366,855'],
 ['23',
  'Dec 17, 2014',
  'The Hobbit: The Battle of the Five Armies',
  '$250,000,000',
  '$255,119,788',
  '$945,577,621'],
 ['24',
  'Apr 14, 2017',
  'The Fate of the Furious',
  '$250,000,000',
  '$225,764,765',
  '$1,234,846,267'],
 ['25',
  'Jun 28, 2006',
  'Superman Returns',
  '$232,000,000',
  '$200,120,000',
  '$374,085,065'],
 ['26',
  'May 26, 2017',
  'Pirates of the Caribbean: Dead Men Tell No Tales',
  '$230,000,000',
  '$172,558,876',
  '$788,241,137'],
 ['27',
  'Nov 14, 2008',
  'Quantum of Solace',
  '$230,000,000',
  '$169,368,427',
  '$591,692,078'],
 ['28',
  'May 4, 2012',
  'The Avengers',
  '$225,000,000',
  '$623,279,547',
  '$1,517,935,897'],
 ['29',
  'Jul 7, 2006',
  'Pirates of the Caribbean: Dead Mans Chest',
  '$225,000,000',
  '$423,315,812',
  '$1,066,215,812'],
 ['30',
  'Jun 14, 2013',
  'Man of Steel',
  '$225,000,000',
  '$291,045,518',
  '$667,999,518'],
 ['31',
  'May 16, 2008',
  'The Chronicles of Narnia: Prince Caspian',
  '$225,000,000',
  '$141,621,490',
  '$417,341,288'],
 ['32', 'Jul 17, 2020', 'Tenet', '$224,000,000', '$0', '$0'],
 ['33',
  'Jul 3, 2012',
  'The Amazing Spider-Man',
  '$220,000,000',
  '$262,030,663',
  '$757,890,267'],
 ['34',
  'May 18, 2012',
  'Battleship',
  '$220,000,000',
  '$65,233,400',
  '$313,477,717'],
 ['35',
  'Jun 21, 2017',
  'Transformers: The Last Knight',
  '$217,000,000',
  '$130,168,683',
  '$602,893,340'],
 ['36',
  'Jun 12, 2015',
  'Jurassic World',
  '$215,000,000',
  '$652,270,625',
  '$1,648,854,864'],
 ['37',
  'May 25, 2012',
  'Men in Black 3',
  '$215,000,000',
  '$179,020,854',
  '$654,213,485'],
 ['38',
  'Jun 24, 2009',
  'Transformers: Revenge of the Fallen',
  '$210,000,000',
  '$402,111,870',
  '$836,519,699'],
 ['39',
  'Jun 27, 2014',
  'Transformers: Age of Extinction',
  '$210,000,000',
  '$245,439,076',
  '$1,104,039,076'],
 ['40',
  'May 26, 2006',
  'X-Men: The Last Stand',
  '$210,000,000',
  '$234,362,462',
  '$459,260,946'],
 ['41',
  'May 14, 2010',
  'Robin Hood',
  '$210,000,000',
  '$105,487,148',
  '$322,459,006'],
 ['42',
  'Dec 14, 2005',
  'King Kong',
  '$207,000,000',
  '$218,080,025',
  '$550,517,357'],
 ['43',
  'Dec 7, 2007',
  'The Golden Compass',
  '$205,000,000',
  '$70,107,728',
  '$367,262,558'],
 ['44',
  'Feb 16, 2018',
  'Black Panther',
  '$200,000,000',
  '$700,059,566',
  '$1,348,258,224'],
 ['45',
  'Dec 19, 1997',
  'Titanic',
  '$200,000,000',
  '$659,363,944',
  '$2,208,208,395'],
 ['46',
  'Jun 15, 2018',
  'Incredibles 2',
  '$200,000,000',
  '$608,581,744',
  '$1,242,520,711'],
 ['47',
  'Dec 16, 2016',
  'Rogue One: A Star Wars Story',
  '$200,000,000',
  '$532,177,324',
  '$1,049,102,856'],
 ['48',
  'Jun 17, 2016',
  'Finding Dory',
  '$200,000,000',
  '$486,295,561',
  '$1,021,215,193'],
 ['49',
  'Jun 18, 2010',
  'Toy Story 3',
  '$200,000,000',
  '$415,004,880',
  '$1,068,879,522'],
 ['50',
  'May 3, 2013',
  'Iron Man 3',
  '$200,000,000',
  '$408,992,272',
  '$1,215,392,272'],
 ['51',
  'May 5, 2017',
  'Guardians of the Galaxy Vol 2',
  '$200,000,000',
  '$389,813,101',
  '$862,316,233'],
 ['52',
  'Jun 30, 2004',
  'Spider-Man 2',
  '$200,000,000',
  '$373,524,485',
  '$795,110,670'],
 ['53',
  'Mar 5, 2010',
  'Alice in Wonderland',
  '$200,000,000',
  '$334,191,110',
  '$1,025,491,110'],
 ['54',
  'Nov 8, 2012',
  'Skyfall',
  '$200,000,000',
  '$304,360,277',
  '$1,110,526,981'],
 ['55',
  'Jun 21, 2013',
  'Monsters University',
  '$200,000,000',
  '$268,488,329',
  '$743,588,329'],
 ['56',
  'Mar 8, 2013',
  'Oz the Great and Powerful',
  '$200,000,000',
  '$234,770,996',
  '$490,359,051'],
 ['57',
  'May 23, 2014',
  'X-Men: Days of Future Past',
  '$200,000,000',
  '$233,921,534',
  '$747,862,775'],
 ['58',
  'May 2, 2014',
  'The Amazing Spider-Man 2',
  '$200,000,000',
  '$202,853,933',
  '$708,996,336'],
 ['59',
  'Jun 24, 2011',
  'Cars 2',
  '$200,000,000',
  '$191,450,875',
  '$560,155,383'],
 ['60',
  'Dec 17, 2010',
  'Tron: Legacy',
  '$200,000,000',
  '$172,062,763',
  '$400,062,763'],
 ['61',
  'Nov 13, 2009',
  '2012',
  '$200,000,000',
  '$166,112,167',
  '$757,677,748'],
 ['62',
  'Nov 16, 2018',
  'Fantastic Beasts: The Crimes of Grindelwald',
  '$200,000,000',
  '$159,555,901',
  '$652,220,086'],
 ['63',
  'May 21, 2009',
  'Terminator Salvation',
  '$200,000,000',
  '$125,322,469',
  '$365,491,792'],
 ['64',
  'Jun 17, 2011',
  'Green Lantern',
  '$200,000,000',
  '$116,601,172',
  '$219,535,492'],
 ['65',
  'May 28, 2010',
  'Prince of Persia: Sands of Time',
  '$200,000,000',
  '$90,759,676',
  '$336,359,676'],
 ['66',
  'Jun 29, 2011',
  'Transformers: Dark of the Moon',
  '$195,000,000',
  '$352,390,543',
  '$1,123,790,543'],
 ['67',
  'Jun 9, 2017',
  'The Mummy',
  '$195,000,000',
  '$80,101,125',
  '$409,953,905'],
 ['68',
  'Mar 1, 2013',
  'Jack the Giant Slayer',
  '$195,000,000',
  '$65,187,603',
  '$197,687,603'],
 ['69',
  'Apr 3, 2015',
  'Furious 7',
  '$190,000,000',
  '$353,007,020',
  '$1,518,722,794'],
 ['70',
  'May 16, 2013',
  'Star Trek Into Darkness',
  '$190,000,000',
  '$228,778,661',
  '$467,381,584'],
 ['71',
  'Jun 21, 2013',
  'World War Z',
  '$190,000,000',
  '$202,359,711',
  '$531,514,650'],
 ['72',
  'May 10, 2013',
  'The Great Gatsby',
  '$190,000,000',
  '$144,840,419',
  '$351,040,419'],
 ['73',
  'Nov 6, 2009',
  'Disneys A Christmas Carol',
  '$190,000,000',
  '$137,855,863',
  '$315,709,697'],
 ['74',
  'Jul 12, 2013',
  'Pacific Rim',
  '$190,000,000',
  '$101,802,906',
  '$411,002,906'],
 ['75',
  'Nov 25, 2015',
  'The Good Dinosaur',
  '$187,500,000',
  '$123,087,120',
  '$333,771,037'],
 ['76',
  'May 2, 2008',
  'Iron Man',
  '$186,000,000',
  '$318,604,126',
  '$585,171,547'],
 ['77',
  'Jul 18, 2008',
  'The Dark Knight',
  '$185,000,000',
  '$533,720,947',
  '$1,001,996,207'],
 ['78',
  'May 22, 2008',
  'Indiana Jones and the Kingdom of the Crystal Skull',
  '$185,000,000',
  '$317,101,119',
  '$786,635,413'],
 ['79',
  'Jun 22, 2012',
  'Brave',
  '$185,000,000',
  '$237,282,182',
  '$554,606,532'],
 ['80',
  'Mar 10, 2017',
  'Kong: Skull Island',
  '$185,000,000',
  '$168,052,812',
  '$561,072,059'],
 ['81',
  'Jul 22, 2016',
  'Star Trek Beyond',
  '$185,000,000',
  '$158,848,340',
  '$335,802,233'],
 ['82',
  'Oct 6, 2017',
  'Blade Runner 2049',
  '$185,000,000',
  '$92,054,159',
  '$259,357,408'],
 ['83',
  'May 24, 2019',
  'Aladdin',
  '$182,000,000',
  '$343,962,586',
  '$1,000,162,586'],
 ['84',
  'Nov 3, 2017',
  'Thor: Ragnarok',
  '$180,000,000',
  '$315,058,289',
  '$846,980,024'],
 ['85',
  'Dec 9, 2005',
  'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  '$180,000,000',
  '$291,710,957',
  '$720,539,572'],
 ['86',
  'May 30, 2014',
  'Maleficent',
  '$180,000,000',
  '$241,407,328',
  '$758,536,735'],
 ['87',
  'Nov 18, 2016',
  'Fantastic Beasts and Where to Find Them',
  '$180,000,000',
  '$234,037,575',
  '$802,402,853'],
 ['88',
  'Jun 27, 2008',
  'WALL-E',
  '$180,000,000',
  '$223,808,164',
  '$532,508,025'],
 ['89',
  'Aug 10, 2007',
  'Rush Hour 3',
  '$180,000,000',
  '$140,125,968',
  '$256,585,882'],
 ['90',
  'Jul 1, 2016',
  'The Legend of Tarzan',
  '$180,000,000',
  '$126,643,061',
  '$348,902,025'],
 ['91', 'Nov 23, 2011', 'Hugo', '$180,000,000', '$73,864,507', '$180,047,784'],
 ['92',
  'Jul 21, 2017',
  'Valerian and the City of a Thousand Planets',
  '$180,000,000',
  '$40,479,370',
  '$215,098,356'],
 ['93',
  'Feb 6, 2015',
  'Jupiter Ascending',
  '$179,000,000',
  '$47,482,519',
  '$181,982,519'],
 ['94',
  'Jul 27, 2018',
  'Mission: ImpossibleFallout',
  '$178,000,000',
  '$220,159,104',
  '$787,456,552'],
 ['95',
  'May 27, 2016',
  'X-Men: Apocalypse',
  '$178,000,000',
  '$155,442,489',
  '$542,537,546'],
 ['96',
  'Aug 10, 2018',
  'The Meg',
  '$178,000,000',
  '$145,443,742',
  '$529,530,715'],
 ['97',
  'Jun 6, 2014',
  'Edge of Tomorrow',
  '$178,000,000',
  '$100,206,256',
  '$370,541,256'],
 ['98',
  'Mar 8, 2019',
  'Captain Marvel',
  '$175,000,000',
  '$426,829,839',
  '$1,123,365,437'],
 ['99',
  'Apr 15, 2016',
  'The Jungle Book',
  '$175,000,000',
  '$364,001,123',
  '$962,854,547'],
 ['100',
  'Jun 19, 2015',
  'Inside Out',
  '$175,000,000',
  '$356,461,711',
  '$854,235,992'],
 ['1',
  'Jul 7, 2017',
  'Spider-Man: Homecoming',
  '$175,000,000',
  '$334,201,140',
  '$880,166,350'],
 ['2',
  'Aug 5, 2016',
  'Suicide Squad',
  '$175,000,000',
  '$325,100,054',
  '$746,059,887'],
 ['3', 'May 29, 2009', 'Up', '$175,000,000', '$293,004,164', '$731,463,377'],
 ['4', 'Nov 22, 2017', 'Coco', '$175,000,000', '$209,726,015', '$798,008,101'],
 ['5',
  'Nov 21, 2018',
  'Ralph Breaks The Internet',
  '$175,000,000',
  '$201,091,711',
  '$523,480,372'],
 ['6',
  'Mar 27, 2009',
  'Monsters vs. Aliens',
  '$175,000,000',
  '$198,351,526',
  '$381,687,380'],
 ['7',
  'Jun 16, 2017',
  'Cars 3',
  '$175,000,000',
  '$152,901,115',
  '$383,541,369'],
 ['8',
  'Aug 7, 2009',
  'G.I. Joe: The Rise of Cobra',
  '$175,000,000',
  '$150,201,498',
  '$302,469,017'],
 ['9',
  'Jun 30, 1999',
  'Wild Wild West',
  '$175,000,000',
  '$113,805,681',
  '$221,229,335'],
 ['10',
  'Aug 1, 2008',
  'The Mummy: Tomb of the Dragon Emperor',
  '$175,000,000',
  '$102,491,776',
  '$405,760,225'],
 ['11',
  'Jun 22, 2007',
  'Evan Almighty',
  '$175,000,000',
  '$100,289,690',
  '$174,131,329'],
 ['12',
  'Jul 28, 1995',
  'Waterworld',
  '$175,000,000',
  '$88,246,220',
  '$264,246,220'],
 ['13',
  'May 12, 2017',
  'King Arthur: Legend of the Sword',
  '$175,000,000',
  '$39,175,066',
  '$139,630,336'],
 ['14',
  'Dec 25, 2013',
  '47 Ronin',
  '$175,000,000',
  '$38,362,475',
  '$151,716,815'],
 ['15',
  'Jun 22, 2018',
  'Jurassic World: Fallen Kingdom',
  '$170,000,000',
  '$417,719,760',
  '$1,305,772,799'],
 ['16',
  'Aug 1, 2014',
  'Guardians of the Galaxy',
  '$170,000,000',
  '$333,172,112',
  '$770,867,516'],
 ['17',
  'May 7, 2010',
  'Iron Man 2',
  '$170,000,000',
  '$312,433,331',
  '$621,156,389'],
 ['18',
  'Apr 4, 2014',
  'Captain America: The Winter Soldier',
  '$170,000,000',
  '$259,746,958',
  '$714,401,889'],
 ['19',
  'Jul 11, 2014',
  'Dawn of the Planet of the Apes',
  '$170,000,000',
  '$208,545,589',
  '$710,644,566'],
 ['20',
  'Nov 10, 2004',
  'The Polar Express',
  '$170,000,000',
  '$187,224,605',
  '$311,365,187'],
 ['21',
  'Jun 1, 2012',
  'Snow White and the Huntsman',
  '$170,000,000',
  '$155,136,755',
  '$401,021,746'],
 ['22',
  'Jul 1, 2003',
  'Terminator 3: Rise of the Machines',
  '$170,000,000',
  '$150,358,296',
  '$433,058,296'],
 ['23',
  'May 7, 2004',
  'Van Helsing',
  '$170,000,000',
  '$120,150,546',
  '$300,150,546'],
 ['24',
  'Mar 29, 2019',
  'Dumbo',
  '$170,000,000',
  '$114,727,689',
  '$344,930,005'],
 ['25',
  'May 31, 2019',
  'Godzilla: King of the Monsters',
  '$170,000,000',
  '$109,712,515',
  '$382,515,871'],
 ['26',
  'May 22, 2015',
  'Tomorrowland',
  '$170,000,000',
  '$93,436,322',
  '$206,627,518'],
 ['27',
  'Feb 14, 2019',
  'Alita: Battle Angel',
  '$170,000,000',
  '$85,710,210',
  '$402,971,268'],
 ['28',
  'May 27, 2016',
  'Alice Through the Looking Glass',
  '$170,000,000',
  '$77,042,381',
  '$276,928,112'],
 ['29',
  'May 21, 2010',
  'Shrek Forever After',
  '$165,000,000',
  '$238,736,787',
  '$756,244,673'],
 ['30',
  'Nov 4, 2016',
  'Doctor Strange',
  '$165,000,000',
  '$232,641,920',
  '$676,404,566'],
 ['31',
  'Nov 7, 2014',
  'Big Hero 6',
  '$165,000,000',
  '$222,527,828',
  '$652,127,828'],
 ['32',
  'Mar 26, 2010',
  'How to Train Your Dragon',
  '$165,000,000',
  '$217,581,232',
  '$494,870,992'],
 ['33',
  'Nov 2, 2012',
  'Wreck-It Ralph',
  '$165,000,000',
  '$189,412,677',
  '$496,511,521'],
 ['34',
  'Nov 5, 2014',
  'Interstellar',
  '$165,000,000',
  '$188,017,894',
  '$666,379,375'],
 ['35',
  'Jun 24, 2016',
  'Independence Day: Resurgence',
  '$165,000,000',
  '$103,144,286',
  '$384,169,424'],
 ['36',
  'Jul 29, 2011',
  'Cowboys and Aliens',
  '$163,000,000',
  '$100,368,560',
  '$176,038,324'],
 ['37',
  'Mar 17, 2017',
  'Beauty and the Beast',
  '$160,000,000',
  '$504,014,165',
  '$1,259,199,706'],
 ['38',
  'Jul 2, 2019',
  'Spider-Man: Far From Home',
  '$160,000,000',
  '$335,760,270',
  '$990,522,079'],
 ['39',
  'Dec 21, 2018',
  'Aquaman',
  '$160,000,000',
  '$335,061,807',
  '$1,146,894,640'],
 ['40',
  'May 17, 2007',
  'Shrek the Third',
  '$160,000,000',
  '$322,719,944',
  '$807,330,936'],
 ['41',
  'Jul 16, 2010',
  'Inception',
  '$160,000,000',
  '$292,576,195',
  '$835,524,642'],
 ['42',
  'Nov 20, 2015',
  'The Hunger Games: Mockingjay - Part 2',
  '$160,000,000',
  '$281,723,902',
  '$648,986,787'],
 ['43',
  'May 24, 2013',
  'Fast and Furious 6',
  '$160,000,000',
  '$238,679,850',
  '$789,300,444'],
 ['44',
  'May 16, 2014',
  'Godzilla',
  '$160,000,000',
  '$200,676,069',
  '$529,076,069'],
 ['45',
  'Jun 3, 2011',
  'X-Men: First Class',
  '$160,000,000',
  '$146,408,305',
  '$355,408,305'],
 ['46',
  'Dec 25, 2008',
  'The Curious Case of Benjamin Button',
  '$160,000,000',
  '$127,509,326',
  '$329,631,958'],
 ['47',
  'Jul 14, 2010',
  "The Sorcerer's Apprentice",
  '$160,000,000',
  '$63,150,991',
  '$217,986,320'],
 ['48',
  'May 12, 2006',
  'Poseidon',
  '$160,000,000',
  '$60,674,817',
  '$181,674,817'],
 ['49',
  'Jun 10, 2016',
  'Warcraft',
  '$160,000,000',
  '$47,225,655',
  '$425,522,281'],
 ['50',
  'Sep 30, 2016',
  'Deepwater Horizon',
  '$156,000,000',
  '$61,433,527',
  '$122,603,824'],
 ['51',
  'Dec 10, 2010',
  'The Chronicles of Narnia: The Voyage of the Dawn Treader',
  '$155,000,000',
  '$104,386,950',
  '$418,186,950'],
 ['52',
  'Jul 1, 2015',
  'Terminator: Genisys',
  '$155,000,000',
  '$89,760,956',
  '$432,150,894'],
 ['53',
  'Mar 23, 2018',
  'Pacific Rim: Uprising',
  '$155,000,000',
  '$59,874,525',
  '$290,930,148'],
 ['54',
  'Nov 24, 2004',
  'Alexander',
  '$155,000,000',
  '$34,297,191',
  '$167,297,191'],
 ['55',
  'Jul 14, 2017',
  'War for the Planet of the Apes',
  '$152,000,000',
  '$146,880,162',
  '$489,592,267'],
 ['56',
  'May 25, 2001',
  'Pearl Harbor',
  '$151,500,000',
  '$198,539,855',
  '$449,239,855'],
 ['57',
  'Jul 2, 2007',
  'Transformers',
  '$151,000,000',
  '$319,246,193',
  '$708,272,592'],
 ['58',
  'Jun 2, 2017',
  'Wonder Woman',
  '$150,000,000',
  '$412,563,408',
  '$821,133,378'],
 ['59',
  'Nov 22, 2013',
  'Frozen',
  '$150,000,000',
  '$400,738,009',
  '$1,272,469,910'],
 ['60',
  'Mar 4, 2016',
  'Zootopia',
  '$150,000,000',
  '$341,268,248',
  '$1,019,429,616'],
 ['61',
  'Jul 11, 2007',
  'Harry Potter and the Order of the Phoenix',
  '$150,000,000',
  '$292,137,260',
  '$943,076,457'],
 ['62',
  'Nov 18, 2005',
  'Harry Potter and the Goblet of Fire',
  '$150,000,000',
  '$290,201,752',
  '$897,099,794'],
 ['63',
  'May 15, 2003',
  'The Matrix Reloaded',
  '$150,000,000',
  '$281,553,689',
  '$738,576,929'],
 ['64',
  'Dec 14, 2007',
  'I am Legend',
  '$150,000,000',
  '$256,393,010',
  '$585,532,684'],
 ['65',
  'Nov 23, 2016',
  'Moana',
  '$150,000,000',
  '$248,757,044',
  '$637,517,365'],
 ['66',
  'Jul 1, 2008',
  'Hancock',
  '$150,000,000',
  '$227,946,274',
  '$624,234,272'],
 ['67',
  'Jul 15, 2005',
  'Charlie and the Chocolate Factory',
  '$150,000,000',
  '$206,459,076',
  '$475,825,484'],
 ['68',
  'Jun 29, 2007',
  'Ratatouille',
  '$150,000,000',
  '$206,445,654',
  '$626,549,695'],
 ['69',
  'Nov 8, 2013',
  'Thor: The Dark World',
  '$150,000,000',
  '$206,362,140',
  '$644,602,516'],
 ['70',
  'Jun 15, 2005',
  'Batman Begins',
  '$150,000,000',
  '$205,343,774',
  '$359,142,722'],
 ['71',
  'Jul 31, 2015',
  'Mission: ImpossibleRogue Nation',
  '$150,000,000',
  '$195,042,377',
  '$688,858,992'],
 ['72',
  'Jul 21, 2017',
  'Dunkirk',
  '$150,000,000',
  '$190,068,280',
  '$499,837,368'],
 ['73', 'May 6, 2011', 'Thor', '$150,000,000', '$181,030,624', '$449,326,618'],
 ['74',
  'Nov 7, 2008',
  'Madagascar: Escape 2 Africa',
  '$150,000,000',
  '$180,174,880',
  '$599,680,774'],
 ['75',
  'May 1, 2009',
  'X-Men Origins: Wolverine',
  '$150,000,000',
  '$179,883,157',
  '$374,825,760'],
 ['76',
  'May 22, 2009',
  'Night at the Museum: Battle of the Smithsonian',
  '$150,000,000',
  '$177,243,721',
  '$402,231,063'],
 ['77',
  'May 26, 2011',
  'Kung Fu Panda 2',
  '$150,000,000',
  '$165,249,063',
  '$664,837,547'],
 ['78',
  'May 15, 2015',
  'Mad Max: Fury Road',
  '$150,000,000',
  '$153,636,354',
  '$370,098,020'],
 ['79',
  'May 10, 2019',
  'Pokmon: Detective Pikachu',
  '$150,000,000',
  '$143,733,273',
  '$429,685,360'],
 ['80',
  'Nov 5, 2003',
  'The Matrix Revolutions',
  '$150,000,000',
  '$139,270,910',
  '$427,300,260'],
 ['81',
  'Mar 29, 2018',
  'Ready Player One',
  '$150,000,000',
  '$137,690,172',
  '$579,290,136'],
 ['82',
  'Nov 4, 2005',
  'Chicken Little',
  '$150,000,000',
  '$135,386,665',
  '$310,043,823'],
 ['83',
  'May 5, 2006',
  'Mission: Impossible III',
  '$150,000,000',
  '$133,501,348',
  '$397,501,348'],
 ['84',
  'May 15, 2009',
  'Angels & Demons',
  '$150,000,000',
  '$133,375,846',
  '$490,875,846'],
 ['85',
  'May 14, 2004',
  'Troy',
  '$150,000,000',
  '$133,298,577',
  '$484,161,265'],
 ['86',
  'Jul 1, 2010',
  'The Last Airbender',
  '$150,000,000',
  '$131,772,187',
  '$319,713,881'],
 ['87',
  'Nov 2, 2007',
  'Bee Movie',
  '$150,000,000',
  '$126,631,277',
  '$287,594,577'],
 ['88',
  'Jul 24, 2009',
  'G-Force',
  '$150,000,000',
  '$119,436,770',
  '$292,817,841'],
 ['89',
  'Nov 21, 2008',
  'Bolt',
  '$150,000,000',
  '$114,053,579',
  '$328,015,029'],
 ['90',

In [9]:
len(result)

5793

In [10]:
movies_df = pd.DataFrame(result, columns=['Number', 'Release Date', 'Movie', 'Production Budget', 'Domestic Gross', 'Worldwide Gross'])
movies_df

,Number,Release Date,Movie,Production Budget,Domestic Gross,Worldwide Gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,789,705,275"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Apr 26, 2019",Avengers: Endgame,"$400,000,000","$855,869,749","$2,791,767,021"
3,4,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$65,504,972","$246,209,283"
4,5,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
5,6,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
6,7,"Dec 18, 2015",Star Wars Ep. VII: The Force Awakens,"$306,000,000","$936,662,225","$2,053,311,220"
7,8,"Apr 27, 2018",Avengers: Infinity War,"$300,000,000","$678,815,482","$2,048,134,200"
8,9,"May 24, 2007",Pirates of the Caribbean: At Worlds End,"$300,000,000","$309,420,425","$963,420,425"
9,10,"Nov 17, 2017",Justice League,"$300,000,000","$229,024,295","$655,945,209"
10,11,"Nov 6, 2015",Spectre,"$300,000,000","$200,074,175","$879,620,923"
11,12,"Jul 20, 2012",The Dark Knight Rises,"$275,000,000","$448,139,099","$1,084,439,099"
12,13,"May 25, 2018",Solo: A Star Wars Story,"$275,000,000","$213,767,512","$393,151,347"
13,14,"Jul 2, 2013",The Lone Ranger,"$275,000,000","$89,302,115","$260,002,115"
14,15,"Mar 9, 2012",John Carter,"$275,000,000","$73,058,679","$282,778,100"
15,16,"Nov 24, 2010",Tangled,"$260,000,000","$200,821,936","$586,477,240"
16,17,"May 4, 2007",Spider-Man 3,"$258,000,000","$336,530,303","$894,860,230"
17,18,"May 6, 2016",Captain America: Civil War,"$250,000,000","$408,084,349","$1,140,069,413"
18,19,"Mar 25, 2016",Batman v Superman: Dawn of Justice,"$250,000,000","$330,360,194","$867,500,281"
19,20,"Dec 14, 2012",The Hobbit: An Unexpected Journey,"$250,000,000","$303,003,568","$1,017,003,568"
20,21,"Jul 15, 2009",Harry Potter and the Half-Blood Prince,"$250,000,000","$302,089,278","$935,213,767"
21,22,"Dec 13, 2013",The Hobbit: The Desolation of Smaug,"$250,000,000","$258,366,855","$960,366,855"
22,23,"Dec 17, 2014",The Hobbit: The Battle of the Five Armies,"$250,000,000","$255,119,788","$945,577,621"
23,24,"Apr 14, 2017",The Fate of the Furious,"$250,000,000","$225,764,765","$1,234,846,267"
24,25,"Jun 28, 2006",Superman Returns,"$232,000,000","$200,120,000","$374,085,065"
25,26,"May 26, 2017",Pirates of the Caribbean: Dead Men Tell No Tales,"$230,000,000","$172,558,876","$788,241,137"
26,27,"Nov 14, 2008",Quantum of Solace,"$230,000,000","$169,368,427","$591,692,078"
27,28,"May 4, 2012",The Avengers,"$225,000,000","$623,279,547","$1,517,935,897"
28,29,"Jul 7, 2006",Pirates of the Caribbean: Dead Mans Chest,"$225,000,000","$423,315,812","$1,066,215,812"
29,30,"Jun 14, 2013",Man of Steel,"$225,000,000","$291,045,518","$667,999,518"
...,...,...,...,...,...,...
5763,64,"Aug 1, 1991",Slacker,"$23,000","$1,227,508","$1,227,508"
5764,65,"Dec 31, 2014",Dry Spell,"$22,000",$0,$0
5765,66,"Dec 31, 2003",Flywheel,"$20,000",$0,$0
5766,67,"Jan 4, 2013",All Superheroes Must Die,"$20,000",$0,$0
5767,68,"Apr 21, 2015",The Front Man,"$20,000",$0,$0
5768,69,"Dec 1, 2003",Steel Spirit,"$20,000",$0,$0
5769,70,"Nov 25, 2011",The Ridges,"$17,300",$0,$0
5770,71,"Jun 2, 2006",The Puffy Chair,"$15,000","$194,523","$195,254"
5771,72,"Apr 2, 2010",Breaking Upwards,"$15,000","$115,592","$115,592"
5772,73,"Dec 31, 2014",Stories of Our Lives,"$15,000",$0,$0
5773,74,"Apr 11, 1997",Pink Flamingos,"$12,000","$413,802","$413,802"
5774,75,"Apr 28, 2006",Grip: A Criminal's Story,"$12,000","$1,336","$1,336"
5775,76,"Dec 31, 2007",Tin Can Man,"$12,000",$0,$0
5776,77,"Mar 9, 2001",Dayereh,"$10,000","$673,780","$673,780"
5777,78,"Apr 28, 2006",Clean,"$10,000","$138,711","$138,711"
5778,79,"Jul 6, 2001",Cure,"$10,000","$94,596","$94,596"
5779,80,"May 28, 2004",On the Downlow,"$10,000","$1,987","$1,987"
5780,81,"Apr 1, 1996",Bang,"$10,000",$527,$527
5781,82,"Aug 14, 2008",The Rise and Fall of Miss Thang,"$10,000",$401,$401
5782,83,"May 19, 2015",Family Motocross,"$10,000",$0,$0
5783,84,"Jan 13, 2012",Newlyweds,"$9,000","$4,584","$4,584"
5784,85,"Feb 26, 1993",El Mariachi,"$7,000","$2,040,920","$2,041,928"
5785,86,"Oct 8, 2004",Primer,"$7,000","$424,760","$841,926"
5786,87,"May 26, 2006",Cavite,"$7,000","$70,071","$71,644"
5787,88,"Dec 31, 2004",The Mongol King,"$7,000",$900,$900
5788,89,"Dec 31, 2018",Red 11,"$7,000",$0,$0
5789,90,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495"
5790,91,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338"
5791,92,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0
5792,93,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041"

In [11]:
movies_df.dtypes

Number               object
Release Date         object
Movie                object
Production Budget    object
Domestic Gross       object
Worldwide Gross      object
dtype: object

In [12]:
movies_df['Release Date'] = pd.to_datetime(movies_df['Release Date'])

In [13]:
# Define a function to parse the money
def parse_money(row):
    money = row.replace("$", "")
    money = money.replace(",", "")
    return float(money)

In [14]:
movies_df['Production Budget'] = movies_df['Production Budget'].apply(parse_money)
movies_df['Domestic Gross'] = movies_df['Domestic Gross'].apply(parse_money)
movies_df['Worldwide Gross'] = movies_df['Worldwide Gross'].apply(parse_money)

In [15]:
movies_df

,Number,Release Date,Movie,Production Budget,Domestic Gross,Worldwide Gross
0,1,2009-12-18,Avatar,425000000.0,760507625.0,2.789705e+09
1,2,2011-05-20,Pirates of the Caribbean: On Stranger Tides,410600000.0,241063875.0,1.045664e+09
2,3,2019-04-26,Avengers: Endgame,400000000.0,855869749.0,2.791767e+09
3,4,2019-06-07,Dark Phoenix,350000000.0,65504972.0,2.462093e+08
4,5,2015-05-01,Avengers: Age of Ultron,330600000.0,459005868.0,1.403014e+09
5,6,2017-12-15,Star Wars Ep. VIII: The Last Jedi,317000000.0,620181382.0,1.316722e+09
6,7,2015-12-18,Star Wars Ep. VII: The Force Awakens,306000000.0,936662225.0,2.053311e+09
7,8,2018-04-27,Avengers: Infinity War,300000000.0,678815482.0,2.048134e+09
8,9,2007-05-24,Pirates of the Caribbean: At Worlds End,300000000.0,309420425.0,9.634204e+08
9,10,2017-11-17,Justice League,300000000.0,229024295.0,6.559452e+08
10,11,2015-11-06,Spectre,300000000.0,200074175.0,8.796209e+08
11,12,2012-07-20,The Dark Knight Rises,275000000.0,448139099.0,1.084439e+09
12,13,2018-05-25,Solo: A Star Wars Story,275000000.0,213767512.0,3.931513e+08
13,14,2013-07-02,The Lone Ranger,275000000.0,89302115.0,2.600021e+08
14,15,2012-03-09,John Carter,275000000.0,73058679.0,2.827781e+08
15,16,2010-11-24,Tangled,260000000.0,200821936.0,5.864772e+08
16,17,2007-05-04,Spider-Man 3,258000000.0,336530303.0,8.948602e+08
17,18,2016-05-06,Captain America: Civil War,250000000.0,408084349.0,1.140069e+09
18,19,2016-03-25,Batman v Superman: Dawn of Justice,250000000.0,330360194.0,8.675003e+08
19,20,2012-12-14,The Hobbit: An Unexpected Journey,250000000.0,303003568.0,1.017004e+09
20,21,2009-07-15,Harry Potter and the Half-Blood Prince,250000000.0,302089278.0,9.352138e+08
21,22,2013-12-13,The Hobbit: The Desolation of Smaug,250000000.0,258366855.0,9.603669e+08
22,23,2014-12-17,The Hobbit: The Battle of the Five Armies,250000000.0,255119788.0,9.455776e+08
23,24,2017-04-14,The Fate of the Furious,250000000.0,225764765.0,1.234846e+09
24,25,2006-06-28,Superman Returns,232000000.0,200120000.0,3.740851e+08
25,26,2017-05-26,Pirates of the Caribbean: Dead Men Tell No Tales,230000000.0,172558876.0,7.882411e+08
26,27,2008-11-14,Quantum of Solace,230000000.0,169368427.0,5.916921e+08
27,28,2012-05-04,The Avengers,225000000.0,623279547.0,1.517936e+09
28,29,2006-07-07,Pirates of the Caribbean: Dead Mans Chest,225000000.0,423315812.0,1.066216e+09
29,30,2013-06-14,Man of Steel,225000000.0,291045518.0,6.679995e+08
...,...,...,...,...,...,...
5763,64,1991-08-01,Slacker,23000.0,1227508.0,1.227508e+06
5764,65,2014-12-31,Dry Spell,22000.0,0.0,0.000000e+00
5765,66,2003-12-31,Flywheel,20000.0,0.0,0.000000e+00
5766,67,2013-01-04,All Superheroes Must Die,20000.0,0.0,0.000000e+00
5767,68,2015-04-21,The Front Man,20000.0,0.0,0.000000e+00
5768,69,2003-12-01,Steel Spirit,20000.0,0.0,0.000000e+00
5769,70,2011-11-25,The Ridges,17300.0,0.0,0.000000e+00
5770,71,2006-06-02,The Puffy Chair,15000.0,194523.0,1.952540e+05
5771,72,2010-04-02,Breaking Upwards,15000.0,115592.0,1.155920e+05
5772,73,2014-12-31,Stories of Our Lives,15000.0,0.0,0.000000e+00
5773,74,1997-04-11,Pink Flamingos,12000.0,413802.0,4.138020e+05
5774,75,2006-04-28,Grip: A Criminal's Story,12000.0,1336.0,1.336000e+03
5775,76,2007-12-31,Tin Can Man,12000.0,0.0,0.000000e+00
5776,77,2001-03-09,Dayereh,10000.0,673780.0,6.737800e+05
5777,78,2006-04-28,Clean,10000.0,138711.0,1.387110e+05
5778,79,2001-07-06,Cure,10000.0,94596.0,9.459600e+04
5779,80,2004-05-28,On the Downlow,10000.0,1987.0,1.987000e+03
5780,81,1996-04-01,Bang,10000.0,527.0,5.270000e+02
5781,82,2008-08-14,The Rise and Fall of Miss Thang,10000.0,401.0,4.010000e+02
5782,83,2015-05-19,Family Motocross,10000.0,0.0,0.000000e+00
5783,84,2012-01-13,Newlyweds,9000.0,4584.0,4.584000e+03
5784,85,1993-02-26,El Mariachi,7000.0,2040920.0,2.041928e+06
5785,86,2004-10-08,Primer,7000.0,424760.0,8.419260e+05
5786,87,2006-05-26,Cavite,7000.0,70071.0,7.164400e+04
5787,88,2004-12-31,The Mongol King,7000.0,900.0,9.000000e+02
5788,89,2018-12-31,Red 11,7000.0,0.0,0.000000e+00
5789,90,1999-04-02,Following,6000.0,48482.0,2.404950e+05
5790,91,2005-07-13,Return to the Land of Wonders,5000.0,1338.0,1.338000e+03
5791,92,2015-09-29,A Plague So Pleasant,1400.0,0.0,0.000000e+00
5792,93,2005-08-05,My Date With Drew,1100.0,181041.0,1.810410e+05

In [16]:
movies_df.dtypes

Number                       object
Release Date         datetime64[ns]
Movie                        object
Production Budget           float64
Domestic Gross              float64
Worldwide Gross             float64
dtype: object

In [17]:
movies_df.sort_values(by='Release Date', ascending=False, inplace=True)

In [18]:
movies_df

,Number,Release Date,Movie,Production Budget,Domestic Gross,Worldwide Gross
675,76,2020-12-31,355,75000000.0,0.0,0.0
197,98,2020-12-31,Moonfall,150000000.0,0.0,0.0
1209,10,2020-12-31,Hannibal the Conqueror,50000000.0,0.0,0.0
2036,37,2020-09-30,Unhinged,29000000.0,0.0,0.0
31,32,2020-07-17,Tenet,224000000.0,0.0,0.0
539,40,2020-02-21,Call of the Wild,82000000.0,0.0,0.0
484,85,2019-12-31,Army of the Dead,90000000.0,0.0,0.0
1548,49,2019-12-31,Down Under Cover,40000000.0,0.0,0.0
3320,21,2019-12-31,Rogue City,13000000.0,0.0,0.0
3524,25,2019-12-31,Eli,11000000.0,0.0,0.0
2336,37,2019-12-31,Reagan,25000000.0,0.0,0.0
1211,12,2019-11-22,The Rhythm Section,50000000.0,0.0,0.0
956,57,2019-11-08,Midway,59500000.0,0.0,0.0
1210,11,2019-11-08,Arctic Dogs,50000000.0,0.0,0.0
3468,69,2019-10-11,Gisaengchung,11800000.0,0.0,88480000.0
1212,13,2019-09-20,Ad Astra,49800000.0,0.0,0.0
1547,48,2019-09-13,The Goldfinch,40000000.0,0.0,0.0
674,75,2019-08-30,PLAYMOBIL,75000000.0,0.0,0.0
3170,71,2019-08-14,Blinded by the Light,15000000.0,0.0,0.0
480,81,2019-07-26,Once Upon a Timein Hollywood,90000000.0,16850000.0,16850000.0
2893,94,2019-07-12,Crawl,17000000.0,28597793.0,38497793.0
137,38,2019-07-02,Spider-Man: Far From Home,160000000.0,335760270.0,990522079.0
1992,93,2019-06-21,Anna,30000000.0,7638768.0,19986597.0
3957,58,2019-06-21,Burn Your Maps,8000000.0,0.0,0.0
1543,44,2019-06-21,Kursk,40000000.0,0.0,5213785.0
334,35,2019-06-14,Men in Black: International,110000000.0,78625602.0,250330133.0
1955,56,2019-06-14,Shaft,30000000.0,21128796.0,21128796.0
4499,100,2019-06-07,Late Night,4000000.0,15219609.0,16896083.0
549,50,2019-06-07,The Secret Life of Pets 2,80000000.0,153046255.0,320006352.0
3,4,2019-06-07,Dark Phoenix,350000000.0,65504972.0,246209283.0
...,...,...,...,...,...,...
5357,58,1942-08-13,Bambi,858000.0,102797000.0,268000000.0
5164,65,1941-10-28,How Green Was My Valley,1250000.0,0.0,0.0
4878,79,1940-11-13,Fantasia,2280000.0,83320000.0,83320000.0
4911,12,1940-08-30,Boom Town,2000000.0,9172000.0,9172000.0
5156,57,1940-03-21,Rebecca,1288000.0,6000000.0,6002370.0
4877,78,1940-02-09,Pinocchio,2289247.0,84300000.0,84300000.0
4577,78,1939-12-15,Gone with the Wind,3900000.0,198680470.0,390525192.0
5078,79,1939-10-17,Mr. Smith Goes To Washington,1500000.0,9000000.0,9000000.0
4798,99,1939-08-25,The Wizard of Oz,2777000.0,34063405.0,34305476.0
5059,60,1938-09-01,You Can't Take It With You,1644000.0,4000000.0,4000000.0
4927,28,1938-05-24,Alexander's Ragtime Band,2000000.0,4000000.0,4000000.0
5127,28,1937-12-21,Snow White and the Seven Dwarfs,1488000.0,184925486.0,184925486.0
5190,91,1936-10-20,The Charge of the Light Brigade,1200000.0,0.0,0.0
5141,42,1936-06-26,San Francisco,1300000.0,2868000.0,5273000.0
5107,8,1936-02-05,Modern Times,1500000.0,163245.0,199747.0
5416,17,1935-09-06,Top Hat,609000.0,1782000.0,3202000.0
5548,49,1934-02-22,It Happened One Night,325000.0,2500000.0,2500000.0
5407,8,1933-04-07,King Kong,672000.0,10000000.0,10000650.0
5513,14,1933-03-09,42nd Street,439000.0,1438000.0,2281000.0
5629,30,1933-02-09,She Done Him Wrong,200000.0,2000000.0,2000000.0
5434,35,1931-12-26,Mata Hari,558000.0,900000.0,900000.0
4569,70,1930-11-15,Hell's Angels,4000000.0,0.0,0.0
5535,36,1929-02-01,The Broadway Melody,379000.0,2800000.0,4358000.0
4994,95,1927-08-12,Wings,2000000.0,0.0,0.0
4579,80,1925-12-30,Ben-Hur: A Tale of the Christ,3900000.0,9000000.0,9000000.0
5617,18,1925-11-19,The Big Parade,245000.0,11000000.0,22000000.0
5694,95,1920-09-17,Over the Hill to the Poorhouse,100000.0,3000000.0,3000000.0
5625,26,1916-12-24,"20,000 Leagues Under the Sea",200000.0,8000000.0,8000000.0
5534,35,1916-09-05,Intolerance,385907.0,0.0,0.0
5688,89,1915-02-08,The Birth of a Nation,110000.0,10000000.0,11000000.0

In [19]:
movies_df.to_csv('movies_list.csv', index=False)

In [20]:
# Get 2018 movies
movies_2018 = movies_df[movies_df['Release Date'].dt.year == 2018]

In [21]:
movies_2018.to_csv('movies_2018.csv', index=False)